function [fitresult, gof] = create_fit_fan(flow_rate, power)
%CREATEFIT(FLOW_RATE,POWER)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : flow_rate
%      Y Output: power
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Jun-2021 10:15:16


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( flow_rate, power );

% Set up fittype and options.
ft = fittype( {'(x)^3', '(x)^2', 'x', '1'}, 'independent', 'x', 'dependent', 'y', 'coefficients', {'a', 'b', 'c', 'd'} );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'power vs. flow_rate', 'Fitted Model', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'flow_rate', 'Interpreter', 'none' );
ylabel( 'power', 'Interpreter', 'none' );
grid on


