clear
close all
clc
tic
setpoints = struct('T', 40, 'phi', 0.50);
settings = struct(...
    'setpoints', setpoints,...
    'T_g0_sim', 20,...
    'T_o', 20,...
    'T_h0', 50,...
    'T_s', 1,...
    'N', 30*20,... % 30=1min irl
    'off', 1e6,...
    'simulation', false,...
    'ni', true,...
    'arduino', true);
settings.max_iterations = settings.N/settings.T_s;
settings.stop_at = settings.off/settings.T_s; % (Iteration)

data = arda_numerical(settings);

price = 0.1036;  % $/kWh
cost = 0;
for i = 1:numel(data.P_h)
   % Needs to be adjusted to account for when Ts is not 1 sec
   cost = cost + price * data.P_h(i)/(1000*60*60);
end
fprintf('Cost for this run: $%.8f\n', cost)
toc

times = [20  47.9;...
         60 123.4];